- app.rb
- bin/convert-grid.rb
- bin/generate-id.rb
- config/index-template.json
removed grid from local, added to external id hash. Added back leading zero to the id format
> added changes

- app.rb
> define release_stage

- .travis.yml
- Dockerfile
- manage.py
- rorapi/management/commands/convertgrid.py
- rorapi/management/commands/downloadgrid.py
- rorapi/management/commands/indexgrid.py
- rorapi/management/commands/setup.py
- rorapi/models.py
- rorapi/queries.py
- rorapi/settings.py
- rorapi/tests/tests_models.py
- rorapi/tests/tests_queries.py
- rorapi/tests/tests_views.py
- rorapi/tests/utils.py
- rorapi/tests_functional/evaluation.py
- rorapi/tests_functional/tests_matching.py
- rorapi/tests_functional/tests_search.py
- rorapi/tests_integration/tests.py
- rorapi/tests_integration/tests_data_dump.py
- rorapi/tests_integration/tests_search.py
- rorapi/views.py
Format existing code with YAPF + add YAPF check to Travis build.
> Code formatting by YAPF

- rorapi/queries.py
- rorapi/settings.py
- rorapi/tests/tests_queries.py
- rorapi/tests_integration/tests.py
fixes https://github.com/ror-community/ror-api/issues/13
> Limit page parameter values

- rorapi/management/commands/convertgrid.py
- rorapi/models.py
- rorapi/settings.py
- rorapi/tests_integration/tests_data_dump.py
New ROR dump for the new GRID release version 2019-10-06
> ROR dump for 2019/10 GRID release

- rorapi/views.py
> Check ES as part of heartbeat check

- .github/workflows/dev.yml
- .github/workflows/master.yml
Migrate continuous integration from Travis CI to GitHub Actions.
closes: #134
I found that docker-compose doesn't work seamlessly with GitHub Actions, so the workflow is slightly different than in the Travis script (first test then build container, rather than the other way around).
Added `ror/services/api/_ror-api.auto.tfvars.tmpl` and `ror/services/api/_ror-api-dev.auto.tfvars.tmpl` to `ror-community/new-deployment`. Disabled Travis CI automatic integration.
- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure …
> GitHub Actions for deployment

- .travis.yml
- rorapi/index_template.json
- rorapi/management/commands/convertgrid.py
- rorapi/models.py
- rorapi/queries.py
- rorapi/settings.py
- rorapi/tests/data/test_data_retrieve.json
- rorapi/tests/data/test_data_search.json
- rorapi/tests/tests_models.py
- rorapi/tests/tests_views.py
- rorapi/tests_functional/tests_matching.py
- rorapi/tests_integration/tests.py
- rorapi/tests_integration/tests_data_dump.py
Merging changes of bringing in code that indexes and displays all active organizations metadata with github actions
> Test dev merge

- .github/workflows/dev.yml
- README.md
Trigger new staging deployment to pick up TF env var name changes
> Merge dev to staging

- rorapi/es_utils.py
- rorapi/index_template.json
- rorapi/queries.py
- rorapi/tests/tests_es_utils.py
- rorapi/tests/tests_queries.py
- Add query.advanced parameter, which allow fielded search
- Change indexing for links and wikipedia_url to allow partial matches
- Change indexing for ISNIs to strip whitespace
> Advanced search

- rorapi/index_template.json
- rorapi/queries.py
- rorapi/tests/tests_queries.py
- Validate field names in query.advanced
- Change indexing for relationships.label to allow partial matches
> add field name validation to advanced search

- rorapi/index_template.json
- Revert ISNI indexing to keyword type
> revert change to ISNI indexing

- rorapi/management/commands/indexrordump.py
- rorapi/tests/tests_matching.py
- Remove auth header from Github data dump request
> Merge dev to staging: Remove auth header

- README.md
- rorapi/management/commands/indexror.py
- Update readme
- Update index name in incremental indexing command
> Updates to api v2

- .github/workflows/dev.yml
- .github/workflows/release.yml
- .github/workflows/staging.yml
- Use correct tests path in staging and prod release workflows
> Merge dev to staging: Update workflow file

- .gitignore
- docker-compose.yml
Add volume for ES container so indices persist after container is removed
> Persist ES volume

- rorapi/common/es_utils.py
- rorapi/common/queries.py
Closes: https://github.com/ror-community/ror-roadmap/issues/240 
used `v1.52-2024-09-16-ror-data` dataset for the testing locally.
> Added default sort for organization api on id field

- rorapi/common/record_utils.py
- rorapi/common/views.py
- rorapi/tests/tests_integration/tests_v2.py
- rorapi/v2/models.py
- rorapi/v2/record_constants.py
- Remove print statement
- Remove sorting for locations field
- Change heartbeat view to check for index instead of retrieving orgs
> Remove locations sort & update heartbeat view

- rorapi/common/record_utils.py
- rorapi/common/views.py
- rorapi/tests/tests_integration/tests_v2.py
- rorapi/v2/models.py
- rorapi/v2/record_constants.py
- Remove print statement
- Remove sorting for locations field
- Change heartbeat view to check for index instead of retrieving orgs
> Merge dev to staging: Heartbeat & locations sorting changes

- requirements.txt
- rorapi/common/views.py
- rorapi/settings.py
> Client ID registration: Email Setup
